### PR TITLE
Clean README

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

I removed duplicated information and cleaned a few things.

### CODE REVIEW

**Comment by hslbck** [comment]
thanks 👍

**Comment by zapashcanon** [comment]
Argh, sorry, didn't think you would merge so quickly, just pushed the last version.. :/

**Comment by hslbck** [comment]
on rare occasions I react quickly :D

**Comment by zapashcanon** [comment]
I see that. ;) Will open a new PR. After this, I think the only thing missing for the Debian packaging will be the source of the .png icon used on the GNOME Shell extension website. \o/

**Comment by hslbck** [comment]
where is this icon referenced? Maybe removing the reference is enough. Otherwise I can provide the icon in the next days.
I will upload a new fix for #33. If this works, it's probably better for you to package this version. Should I create a new release then?

**Comment by zapashcanon** [comment]
It is referenced because of the file: `radio@hslbck.gmail.com/icons/extension-page-icon.png` ; I think the only way to remove the "reference" is to remove the file. But I don't know if it's possible, as I imagine that the GNOME Shell extension website is relying on it ?

Yep', it will probably be better to package the version with the fix. I guess you'd just have to create a new release when you think everything is ready, and I'll package from it.

**Comment by hslbck** [comment]
updated the icons. You should be able to open them again.

The extension website is not relying on the image. The extension upload and image upload are independent from each other.

Ok, when the new fix works I think I will package a new version

**Comment by zapashcanon** [comment]
Yep' I can open them again, thanks.

So, there's not need for the icon in this repo and it's reproducible from the `.svg` source by just changing the color and exporting as png, so, the best thing to do is probably to delete it, no ? Check-all-the-things will stop complaining about the absence of source by doing so.

**Pull request merged**
