### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by Zerrossetto**

### CODE REVIEW

**Comment by hslbck** [comment]
thanks for the translation 👍

**Comment by zapashcanon** [comment]
@Zerrossetto, I'll open a PR to add copyright, it'll look like:

```js
# Copyright (C) 2017 Duilio Rumbazzi <email address>
# This file is distributed under the same license as the gnome-shell-extension-radio package.
```

Do you have an email address I can add ? Or do you prefer not to publish it ?

(Or I can just let you add it if you want !)

**Comment by Zerrossetto** [comment]
Hi, if possible I would like to leave it like this, if not possible I'll go with the fake github email: Zerrossetto@users.noreply.github.com
Is it ok?

**Comment by zapashcanon** [comment]
It's possible to let it empty, but I'll add the fake email, so someone reading it will know how to find you. ;)

**Pull request merged**
