### PR TITLE
Remove hardcoded strings

### LINKED ISSUE #81: Hardcoded english strings
Hi,

Some strings displayed to the end-user are hard-coded and thus, not translated.

E.g. in `player.js`:

```js
case Gst.MessageType.ERROR:
      MyE.radioMenu._stop();
      MyE.radioMenu.playLabel.set_text("Stream error");
      break;
case Gst.MessageType.EOS:
      MyE.radioMenu._stop();
      MyE.radioMenu.playLabel.set_text("End of stream");
```

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

Fix #81.

I removed the hard-coded strings, updated the `.po` files and updated the french translation.

Should not be merged yet, because #80 should be merged first and I've got a few things to fix.

### CODE REVIEW

**Comment by hslbck** [comment]
Still in progress?

**Comment by zapashcanon** [comment]
You should merge #86 first, then I'll rebase, then it should be OK as it seems to work.

The only thing is, the text is not fully displayed (my screen is small):

capture du 2017-11-21 13-29-19

I can't test for "End of stream" as I don't know how to make this error happen. But it should work.

**Comment by hslbck** [comment]
The extension has a fixed size, so it won't fit on other screens, too. Could the translation be shortened?

There is an additional text "Missing plugin" in player.js which we should translate as well

**Comment by hslbck** [comment]
Merged it, thank a lot!

**Pull request merged**
